# Generated by Django 5.2.3 on 2025-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='mode',
            field=models.CharField(choices=[('phone', 'Phone (Mobile Money)'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='phone', max_length=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
