# Generated by Django 5.2.3 on 2025-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_payroll_mode_payroll_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'pay_period_start', 'pay_period_end')},
        ),
    ]
